Changed crc library from 'PyCRC' to 'crc' due to error message (ModuleNotFoundError: No module named 'PyCRC'). Seems abandoned? Changed serial library from 'serial' to 'pyserial' due to error message (AttributeError: module 'serial' has no attribute 'Serial')